---
- name: copy launcher build script
  copy:
    src: ../scripts/build_launchers.py
    dest: /tmp

- name: build launchers
  shell: python build_launchers.py
  ignore_errors: yes
  args:
    chdir: /tmp