---
- name: install wireless tools from packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - aircrack-ng
    - kismet
    - libnl-3-dev
    - libpcap-dev
    - libsqlite3-dev
    - libssl-dev
    - libssl1.0-dev
    - libnl-genl-3-dev
    - tshark
    - wireshark

- name: install python2 packages for wireless tools
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - netifaces
    - psycopg2
    - psutil
    - scapy

- name: get pixiewps
  git:
    repo: https://github.com/wiire/pixiewps
    dest: /opt/pixiewps
    update: yes

- name: install pixiewps
  shell: make && make install
  args:
    chdir: /opt/pixiewps/src

- name: get reaver
  git:
    repo: https://github.com/t6x/reaver-wps-fork-t6x
    dest: /opt/reaver
    update: yes

- name: install reaver
  shell: ./configure && make && make install
  args:
    chdir: /opt/reaver/src

- name: get pyrit
  git:
    repo: https://github.com/JPaulMora/Pyrit
    dest: /opt/pyrit
    update: yes

- name: build pyrit
  shell: python setup.py clean && python setup.py build
  args:
    chdir: /opt/pyrit

- name: install pyrit
  shell: python setup.py install
  args:
    chdir: /opt/pyrit

- name: get cowpatty
  git:
    repo: https://github.com/roobixx/cowpatty
    dest: /opt/cowpatty
    update: yes

- name: install cowpatty
  shell: make
  args:
    chdir: /opt/cowpatty

- name: get wifite
  git:
    repo: https://github.com/derv82/wifite
    dest: /opt/wifite
    update: yes

- name: get wifisuite 
  git:
    repo: https://github.com/NickSanzotta/WiFiSuite
    dest: /opt/wifisuite
    update: yes

- name: install wifisuite
  shell: python setup.py install --record install.log
  args:
    chdir: /opt/wifisuite

- name: get hostapd-wpe
  git:
    repo: https://github.com/OpenSecurityResearch/hostapd-wpe
    dest: /tmp/hostapd-wpe
    update: yes

- name: get and extract hostapd
  unarchive:
    src: https://sources.voidlinux.eu/hostapd-2.6/hostapd-2.6.tar.gz
    dest: /tmp
    remote_src: True

- name: patch hostapd
  shell: patch -p1 < ../hostapd-wpe/hostapd-wpe.patch
  args:
    chdir: /tmp/hostapd-2.6

- name: build patched hostapd
  shell: make
  args:
    chdir: /tmp/hostapd-2.6/hostapd

- name: bootstrap hostapd-wpe certs
  shell: ./bootstrap
  args:
    chdir: /tmp/hostapd-wpe/certs