---
- name: get oh-my-zsh
  shell: sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

- name: get powerline for zsh
  git:
    repo: https://github.com/bhilburn/powerlevel9k
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
    update: yes

- name: get fonts
  git:
    repo: https://github.com/ryanoasis/nerd-fonts
    dest: /tmp/nerd-fonts

- name: install fonts
  shell: ./install.sh DroidSansMono
  ignore_errors: yes
  args:
    chdir: /tmp/nerd-fonts

- name: cleanup font installer
  file:
    path: /tmp/nerd-fonts
    state: absent

- name: get tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: configure tmux
  template:
    src: tmux.conf.template
    dest: ~/.tmux.conf

- name: set .vimrc
  template:
    src: vimrc.template
    dest: ~/.vimrc

- name: set .zshrc
  template:
    src: zshrc.template
    dest: ~/.zshrc